### ISSUE TITLE
Feature Request: show configured button image in UI

### ISSUE THREAD

**Issue by matt-cahill** [DCS-Skunkworks/DCSFlightpanels#55]
Building a profile can be very confusing if you have to constantly refer back to the device itself. Allowing the UI to display the configured icon would make it easier to know which button you are working on.

**Comment by jdahlblom** [comment]
I did a try, it didn't work fully but damn it was horrible. If you only have nice images then it may be OK but otherwise it is confusing. Also, the dots indicating configuration has to go then.
I would at this point say this is a no-go because it isn't critical for getting the most out of Stream Deck. And it too would add to the CPU load of DCSFP.
