### ISSUE TITLE
M2000-C Radio issues

### ISSUE THREAD

**Issue by doramail** [DCS-Skunkworks/DCSFlightpanels#62]
VHF radio of the Mirage 2000-C do not cycle from channel 20 to chanel 1. When reaching channel 20 manually, you should be able to switch to channel 1 but unfortunately, you have to go back from 20 to 1 in back order which is time consuming.
For UHF radio, when in cockpit, radio channel 1 is displayed as channel 0 on the Flightpanels display.

**Comment by WarLord211** [comment]
The VHF is an DCS_BIOS bug i fix it and upload it to the 0.7.00 master branch
the UHF bug is related to Flightpanel.

Here is the BIOS code:
defineSetCommandTumb("UHF_PRESET_KNOB", 20, 3435, 435, 0.05, {0, 1}, {" 1", " 1", " 2", " 3", " 4", " 5", " 6", " 7", " 8", " 9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"}, true, "UHF RADIO", "Preset Knob UHF")

its an woraround since at the start of the game 0 is used by the plane. if you change the channel 0 will be ignored by the plane. To have at the start the right number i override the 0 with 1

**Comment by WarLord211** [comment]
BIOS fix uploaded.
Thx for the report

**Comment by doramail** [comment]
Thank you very much for the updates of the Mirage VHF/UHF radios.
I tested it and it works as you said.
The workaround for the UHF radio works too.
Best regards.
