### ISSUE TITLE
alpha regression: open dialogue no longer remembers last location

### ISSUE THREAD

**Issue by matt-cahill** [DCS-Skunkworks/DCSFlightpanels#72]
in previous versions of DCSFP the open dialogue defaults to the last used location but in the recent alpha versions it always defaults to "Documents"

**Comment by jdahlblom** [comment]
Which open dialog. There are many.

**Comment by jdahlblom** [comment]
Please create new issues if you find more bugs regarding export & import.  Thanks.

**Comment by matt-cahill** [comment]
This is in the main profile open dialog, the one from the Open the File menu.

**Comment by jdahlblom** [comment]
I've noticed a change too but because the settings are dependent on version I assumed it was a "thingy" only when I was developing (compiling all the time).
But now that I try to reproduce the behaviour I can't. It always loads the profile.

**Comment by WarLord211** [comment]
i have the same issue too. 
Everytime i click on the Open Profile button, i must navigate to the place were i stored my Profiles.

on previous version you have to do this first time and later it remember the location.
Means when you hit the Open Profile button you were in the folder were the are stored.

**Comment by WarLord211** [comment]
i did some investigation: 

When you first start (after install) DCSFlightpanels 3.6.22 and open an profile via the open button. 
![2020-07-11](https://user-images.githubusercontent.com/10798954/87221742-a7f6a700-c36e-11ea-8df6-a2f078beef4a.png)

you have to navigate to the folder were the profiles stored. After that, every time you hit the open button this folder is remembered and you never have to navigate. even when to program was closed an reopened

after 3.6.22 you always have to navigate since dcsfp forget the place/folder path

**Comment by WarLord211** [comment]
its solved in 4.1.12
