### ISSUE TITLE
Microsoft Flight 2020 Support

### ISSUE THREAD

**Issue by cgibsonmm** [DCS-Skunkworks/DCSFlightpanels#96]
What would it take to start looking into support for 2020

**Comment by konsollfreak** [comment]
Second this. People are pretty desperate for working panels.

**Comment by jdahlblom** [comment]
Does it support communication with the sim engine as DCS do? Spad.next perhaps will support it?

**Comment by jdahlblom** [comment]
As if I happen to have code laying around that can be used you mean? Before I have a resemblance to a concept of proof those guys will have that fixed. As they clearly states in the thread, SimConnect, spad.next etc etc worked in alpha.

**Comment by ZoeESummers** [comment]
@jdahlblom No, that's not what I meant. I meant that the 'lags / stutters / frame rate' issues people are reporting are because they are using 3rd party tools that all hook into the 'SimConnect' api.

As you don't use that (AFAIA) then there is no reason that DCSFlightPanels would cause any of those reported issues. 

That's what I meant.
